name: starship_shooter
description: Flutter starship shooter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  audioplayers: ^5.0.0
  bloc: ^8.1.2
  equatable: ^2.0.5
  flame: ^1.12.0
  flame_audio: ^2.0.5
  flame_behaviors: ^1.0.0
  flame_bloc: ^1.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  intl: ^0.18.0
  mockingjay: ^0.5.0

dev_dependencies:
  bloc_test: ^9.1.4
  flame_test: ^1.12.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/images/klondike_sprites.png
    - assets/licenses/poppins/
