name: starship_shooter
description: Flutter starship shooter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  audioplayers: ^5.0.0
  bloc: ^8.1.2
  equatable: ^2.0.5
  flame: ^1.12.0
  flame_audio: ^2.0.5
  flame_behaviors: ^1.0.0
  flame_bloc: ^1.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  fullscreen_window: ^1.0.4
  google_fonts: ^6.1.0
  intl: ^0.18.0
  mockingjay: ^0.5.0

dev_dependencies:
  bloc_test: ^9.1.4
  flame_test: ^1.15.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  msix: ^3.16.7
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/images/klondike_sprites.png
    - assets/licenses/poppins/

  fonts:
    - family: "04B_03"
      fonts:
        - asset: assets/fonts/04B_03__.TTF

msix_config:
  display_name: Starship Shooter
  publicer_display_name: Nexer AB
  identity_name: com.nexergroup.starship-shooter
  msix_version: 1.0.0.0
  languages: en-us

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/AI-Logo.png"
  web:
    generate: true
    image_path: "assets/images/AI-Logo.png"
  windows:
    generate: true
    image_path: "assets/images/AI-Logo.png"
    icon_size: 256