name: starship_shooter

concurrency:
  group: $-$
  cancel-in-progress: true

on:
#   push:
#     branches:
#       - main
  pull_request:
    branches:
      - main

  push:
  workflow_dispatch:

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: tryy3/flutter-game-jam-2023/.github/workflows/flutter_package.yml@main
    with:
      flutter_channel: stable
      min_coverage: 0
      test_optimization: false
      analyze_directories: "lib"
      runs_on: windows-latest

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
      modified_files_only: false
